config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "pages#home"
  get "contact", to: "pages#contact"
  post "/tinymce_assets", to: "tinymce_assets#create"
  get "cookies", to: "pages#cookies", as: "cookies"
  get "toolkit", to: "toolkit#index"

  resources :contact_messages, only: :create do
    collection { post :validate }
  end

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  namespace :admin do
    root "action_logs#index"
    get "toolkit", to: "toolkit#index"
    resources :admins
    resource :admin_account,                only: [:show, :update], path: :account
    resources :contact_infos,               only: [:index, :create, :edit, :update]
    resources :contact_messages,            only: [:index, :show]
    resources :action_logs,                 only: [:index, :show]
  end

end

app/views/layouts/admin/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert-error">
        <h2><%= "Broj grešaka: #{object.errors.count}" %></h2>
      </div>
      <div class="alert-error-list">
        <% object.errors.full_messages.each do |msg| %>
            <p>* <%= msg %></p>
        <% end %>
      </div>
    </div>
<% end %>

<script>
  $(function(){
    $('#error_explanation').delay(1000).animate({backgroundColor: '#FFFFFF', color: "#c62828"}, 1000);
  });
</script>

app/views/layouts/admin/_footer.html.erb
<footer class="footer">

  <div class="layout--padded">
    <p>Bamboo CMS footer</p>
  </div>

</footer>

app/views/layouts/admin/_header.html.erb
<nav class="navigation">
  <%= link_to "Bamboo Lab", "http://bamboolab.eu", class: "logo--bamboo", target: "_blank" %>

  <div class="navigation__content">
    <div class="navigation__account">
      <%= link_to admin_admin_path(current_admin), class: "account__link" do %>
        <%= image_tag current_admin.image_url(:thumb), class: "account__img" %>
      <% end %>
      <%= inline_svg "icons/shape-arrow-down.svg", class: "account__arrow" %>
    </div>

      <div class="dropdown">
        <%= link_to t('admin_nav.account_options'), admin_admin_account_path, class: "dropdown__link" %>
        <%= link_to t("admin_nav.log_out"), destroy_admin_session_path, data: {method: :delete}, class: "dropdown__link" %>
      </div>

    <div class="navigation__lang">
      <% if I18n.locale == I18n.default_locale %>
        <%= link_to "EN", url_for( :locale => "en" ), class: "lang__link" %>
      <% else %>
        <%= link_to "HR", url_for( :locale => "hr" ), class: "lang__link" %>
      <% end %>
    </div>
  </div>
</nav>

<div class="js_notifications"><%= render 'layouts/admin/notifications' %></div>

<script>
  $('.account__arrow').on('click', function(){
    $(this).toggleClass('active');
    $(".dropdown").animate({height: 'toggle'});
  });

  $(".dropdown").click(function(e){
    e.stopPropagation();
  });

   $(".account__arrow").click(function(e){
    e.stopPropagation();
  });

  $(document).click(function(){
    if($(".account__arrow").hasClass("active")) {
      $(".dropdown").animate({height: 'toggle'});
      $(".account__arrow").removeClass("active");
    }
  });


</script>

app/views/layouts/admin/_navigation.html.erb
<div class="sidebar">
  <nav class="sidebar__content">
    <%= link_to admin_root_path, class: 'sidebar__logo' do %>
      <%= image_tag '' %>
    <% end %>

    <%= active_link_to admin_root_path, class: 'sidebar__link', active: :exact, class_active: 'active-link' do %>
      <%= inline_svg "icons/nav/house-icon.svg", class: 'sidebar__icon' %>
        <%= t('admin_nav.activity') %>
    <% end %>

    <% if current_admin.permitted?(:admins) %>
      <%= active_link_to admin_admins_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/users.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.accounts") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_infos) %>
      <%= active_link_to admin_contact_infos_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/location.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.contact_info") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_contact_messages_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/messages.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.contact_messages") %>
      <% end %>
    <% end %>


    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_toolkit_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/tool-1.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.toolkit") %>
      <% end %>
    <% end %>

    <%= link_to root_path, class: 'sidebar__link' do %>
      <%= inline_svg "icons/nav/exit.svg", class: 'sidebar__icon' %>
      <%= t("admin_nav.go_to_web") %>
    <% end %>
  </nav>
</div>

<style>
    .js_messages_count{
        background: red;
        padding: 3px 5px;
        border-radius: 50px;
    }
</style>

app/views/layouts/admin/_notifications.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) and msg.length > 0 %>
  <div class="message">
    <div class="row">
      <div class="small-12 columns">

        <div class="close js_close_flash">
          <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
            <%= content_tag :p, msg %>
          </div>
        </div>

      </div>
    </div>
  </div>
  <% end %>
<% end %>

<script>
  $("body").on("mousemove touchmove", function(){
    $(".alert-box").delay(3000);
    $(".alert-box").slideUp(500,function() { $(".alert-box").remove() });
    $(".js_close_flash").on("click", function() {
        $(".alert-box").slideUp(500,function() { $(".alert-box").remove() });
    });
  });
</script>

app/views/layouts/admin/dashboard.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="https://www.facebook.com/2008/fbml">

<head>
  <title><%= "Admin | Bamboo CMS" %></title>

  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <%= stylesheet_link_tag 'admin', media: 'all' %>
  <%= javascript_include_tag 'admin' %>

  <!--
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzd4fBjS8aS9V3-_tbiyPq9l2vf8fboS4&callback=initMap"></script>
  -->

  <script src="../maps/omaps/OpenLayers.js"></script>

  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>

<body data-locale="<%= I18n.locale %>">

   <div class="layout--main mobile-splash">
    <%= inline_svg "icons/x2_black.svg" %>
    <p class="text--center text--large strong"><%= t('mobile_dashboard_info') %></p>
    <br>
    <a href="javascript:history.back()" class="btn btn--primary"><%= t('back') %></a>
  </div>

  <div class="<%= 'grid grid--12' unless @navigation_disabled %> hidden--small">

    <%= render 'layouts/admin/navigation' unless @navigation_disabled %>

    <div class="<%= @navigation_disabled ? 'main layout--main' : 'main' %>">
      <%= render 'layouts/admin/header' unless @header_disabled %>

      <div class="grid grid--12 <%= 'main__content' unless @navigation_disabled %>">
        <%= yield %>
      </div>

      <%#= render 'layouts/admin/footer' unless @footer_disabled %>
    </div>

  </div>

  <div id="popup-message"></div>

<%#= render 'layouts/modal' %>
</body>
</html>