config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "pages#home"
  get "contact", to: "pages#contact"
  post "/tinymce_assets", to: "tinymce_assets#create"
  get "cookies", to: "pages#cookies", as: "cookies"
  get "toolkit", to: "toolkit#index"

  resources :contact_messages, only: :create do
    collection { post :validate }
  end

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  namespace :admin do
    root "action_logs#index"
    get "toolkit", to: "toolkit#index"
    resources :admins
    resource :admin_account,                only: [:show, :update], path: :account
    resources :contact_infos,               only: [:index, :create, :edit, :update]
    resources :contact_messages,            only: [:index, :show]
    resources :action_logs,                 only: [:index, :show]
  end

end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
	include LogActions

	validates_presence_of :name, :address, :email
	validates :longitude, inclusion: -180..180, allow_nil: true
	validates :latitude, inclusion: -90..90, allow_nil: true

end

app/controllers/admin/contact_infos_controller.rb
class Admin::ContactInfosController < Admin::BaseController
  before_action :set_contact_info, only: [:edit, :update]

  def index
    @contact_info = ContactInfo.first_or_initialize
  end

  def edit
    respond_to do |format|
      format.js { render 'admin/contact_infos/edit.js.erb', object: @contact_info.id }
    end
  end

  def update
    respond_to do |format|
      if @contact_info.update(contact_info_params)
        format.js { render js: "location.reload();" }
      else
        format.js { render 'admin/contact_infos/edit.js.erb', object: @contact_info.id }
      end 
    end
  end

  private

  def set_contact_info
    @contact_info = ContactInfo.first_or_initialize
  end

  def contact_info_params
    params.require(:contact_info).permit(:name, :address, :email, :phone, :longitude, :latitude)
  end

end

app/views/admin/contact_infos/_edit.html.erb
<div class="contact__content">
	<header class="header header--small">
		<%= link_to admin_contact_infos_path, class: "btn btn--back" do %>
			<div class="arrow--left"></div>
		<% end %>

		<div class="header__content">
			<h1><%= t('nav.contacts') %></h1>
			<p><%= t('nav.edit') %></p>
		</div>
	</header>

	<div class="section__wrap--10">

		<section class="section section--col section--padded">
			
			<%= form_for [:admin, @contact_info], remote: true do |f| %>
				<h3>OpenStreetMap</h3>
				<div id="js_osm" style="height:350px"> </div>

				<div class="form__field">
					<fieldset class="fieldset">
						<legend class="label"><%= t('contact_info.map_coordinates') %></legend>
				
						<div class="form__field form__coordinate">
							<%= f.label :longitude, class: "label" %>
							<div class="input__wrapper">
			          			<%= link_to "-", "javascript:void(0);", class: "btn btn--primary btn--small btn__coordinate", onmousedown: "coordinateSetOnMap('contact_info_longitude', '-')", onmouseup: "stopCoordinates()" %>
								<%= f.number_field :longitude, class: "input js_longitude input__coordinate", min: "-180", max: "180", step: "0.000001" %>
			          			<%= link_to "+", "javascript:void(0);", class: "btn btn--primary btn--small btn__coordinate", onmousedown: "coordinateSetOnMap('contact_info_longitude', '+')" , onmouseup: "stopCoordinates()" %>
			          		</div>
						</div>

						<div class="form__field form__coordinate">
							<%= f.label :latitude, class: "label" %>
							<div class="input__wrapper">
			          			<%= link_to "-", "javascript:void(0);", class: "btn btn--primary btn--small btn__coordinate", onmousedown: "coordinateSetOnMap('contact_info_latitude', '-')", onmouseup: "stopCoordinates()"%>
								<%= f.number_field :latitude, class: "input js_latitude input__coordinate", min: "-90", max: "90", step: "0.000001" %>
			          			<%= link_to "+", "javascript:void(0);", class: "btn btn--primary btn--small btn__coordinate", onmousedown: "coordinateSetOnMap('contact_info_latitude', '+')", onmouseup: "stopCoordinates()" %>
			          		</div>
						</div>
								<em class="text--small"><%= t('contact_info.map_coordinates_desc') %></em>
					</fieldset>
				</div>

				<div class="form__field">
					<%= f.label :name, class: "label" %>
					<%= f.text_field :name, class: "input"%>
				</div>

				<div class="form__field">
					<%= f.label :email, class: "label" %>
					<%= f.text_field :email, class: "input"%>
				</div>

				<div class="form__field">
					<%= f.label :address, class: "label" %>
					<%= f.text_field :address, class: "input"%>
				</div>

				<div class="form__field">
					<%= f.label :phone, class: "label" %>
					<%= f.text_field :phone, class: "input"%>
				</div>


				<%= f.submit class: "btn btn--primary sticky-submit", value: t("save") %>

			<% end %>
		</section>
	</div>

</div>

app/views/admin/contact_infos/edit.js.erb
$(function() {
  // empty old content and add form
  $('.js_contact_content').empty()
    .append('<%= j render partial: "admin/contact_infos/edit.html.erb" %>')

  // pin depends on input fields and is not clickable
  // location filed have onchange events  
  var l = {
    latitude: $(".js_latitude").val(),
    longitude: $(".js_longitude").val()
  };

  var globalIcon = new OpenLayers.Icon(
    defaultOmInactiveMarker.icon, 
    defaultOmActiveMarker.size, 
    new OpenLayers.Pixel(-(defaultOmActiveMarker.size.w/2), - defaultOmActiveMarker.size.h)
  );

  $( ".js_longitude" ).change(function() {
    l.longitude = $( this ).val()

    let lon = l.longitude;
    let lat = l.latitude;
    var position = new OpenLayers.LonLat(lon, lat).transform(
      new OpenLayers.Projection("EPSG:4326"),
      new OpenLayers.Projection("EPSG:900913"),
    );

    var marker = new OpenLayers.Marker(position, globalIcon)
    globalMarkers.clearMarkers();
    globalMarkers.addMarker(marker);
  });

  $( ".js_latitude" ).change(function() {
    l.latitude = $( this ).val()

    let lon = l.longitude;
    let lat = l.latitude;
    var position = new OpenLayers.LonLat(lon, lat).transform(
      new OpenLayers.Projection("EPSG:4326"),
      new OpenLayers.Projection("EPSG:900913"),
    );

    var marker = new OpenLayers.Marker(position, globalIcon)
    globalMarkers.clearMarkers();
    globalMarkers.addMarker(marker);
  });

  var pins = [
    {latitude: l.latitude, longitude: l.longitude}
  ];

  // zoom is optional
  var center = {latitude: l.latitude, longitude: l.longitude, zoom: 10 };

  initOmap("js_osm"); //js_osm is id of div
  oMapAdd({
    pins: pins, 
    center: center, 
  }); // all props optional

  runOnclick();
});

app/views/admin/contact_infos/index.html.erb
<header class="header header--small">
  <h1><%= t('admin_nav.contact_info') %></h1>
</header>

<%#= link_to last_log(@contact_info), [:admin, @contact_info.action_logs.last], class: "btn btn--log", remote: true if @contact_info.action_logs.any? %>

<div class="section__wrap--6">
	<h2 class="main__subtitle--small"><%= t('details') %></h2>

    <div class="js_contact_content">
		<section class="section section--col section--padded">
	     
			<div class="btn__group--edit">
				<%= link_to edit_admin_contact_info_path(@contact_info), class: "btn btn--edit", remote: true do %>
					<%= inline_svg "icons/pen-group-3.svg" %>
				<% end %>
			</div>
			<h3><%= @contact_info.name %></h3>

	    	<div id="js_osm" style="height:250px" > </div>

			<ul class="contact__info">
				<li><%= inline_svg "icons/pin-3-3.svg", class: 'contact__icon' %> <%= @contact_info.address %></li>
				<li><%= inline_svg "icons/at-sign.svg", class: 'contact__icon' %> <%= mail_to @contact_info.email, @contact_info.email, class: "link" %></li>
				<li><%= inline_svg "icons/phone-2.svg", class: 'contact__icon' %> <%= @contact_info.phone %></li>
			</ul>

		</section>
	</div>
</div>

<div class="section__wrap--6">
	<h2 class="main__subtitle--small header--double"><%= t('activity') %></h2>

	<section class="section--col">
		<%= render 'admin/action_logs/action_logs_container', action_logs: @contact_info.action_logs %>
	</section>
</div>

<script>
  var l = {
    latitude: "<%= @contact_info.latitude %>",
    longitude: "<%= @contact_info.longitude %>"
  };

var pins = [
  {latitude: l.latitude, longitude: l.longitude, infoWindow: {
      id: "uniq-id-of-this-infoWindow-"+Date.now(),
      elements: ["<b> <%=@contact_info.name%> </b> "]
    }
  },
  {latitude: 45.571114, longitude: 18.664185, marker: { icon: '../maps/omaps/img/pika_pin.png', size: {w: 30, h: 30} },
    callback: (function() {alert("pika-pika")})  
  },

];

// zoom is optional
var center = {latitude: l.latitude, longitude: l.longitude, zoom: 10 };

initOmap("js_osm"); //js_osm is id of div
oMapAdd({
  pins: pins, 
  center: center, 
}); // all props optional
</script>